apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

secretGenerator:
  - name: video-manager-signalrhub-secret
    behavior: merge
    envs:
      - "./patches/secret.env"