image:
  tag: 6.0.5-debian-11-r1
  
architecture: replicaset
replicaCount: 1
auth:
  rootUser: root
  rootPassword: password
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
readinessProbe:
  initialDelaySeconds: 60