image:
  tag: 3.11.11-debian-11-r0

auth:
  username: user
  password: password
resources:
  requests:
    cpu: "50m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "2048Mi"
readinessProbe:
  initialDelaySeconds: 6