image:
  tag: 7.0.10-debian-11-r1

global:
  redis:
    password: password
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
readinessProbe:
  initialDelaySeconds: 60