apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../aks-dev"
  - "./resources/ingress/ingress.yml"
  - "./resources/ingress/storage-ingress.yml"
  - "./resources/cluster-issuer/lets-encrypt.yml"

images:
  - name: api-gateway
    newName: vspsample.azurecr.io/api-gateway
    newTag: "1"
  - name: community-api
    newName: vspsample.azurecr.io/community-api
    newTag: "1"
  - name: history-api
    newName: vspsample.azurecr.io/history-api
    newTag: "1"
  - name: identity-provider
    newName: vspsample.azurecr.io/identity-provider
    newTag: "1"
  - name: library-api
    newName: vspsample.azurecr.io/library-api
    newTag: "1"
  - name: search-api
    newName: vspsample.azurecr.io/search-api
    newTag: "1"
  - name: storage-api
    newName: vspsample.azurecr.io/storage-api
    newTag: "1"
  - name: subscriptions-api
    newName: vspsample.azurecr.io/subscriptions-api
    newTag: "1"
  - name: users-api
    newName: vspsample.azurecr.io/users-api
    newTag: "1"
  - name: video-manager-api
    newName: vspsample.azurecr.io/video-manager-api
    newTag: "1"
  - name: video-manager-signalrhub
    newName: vspsample.azurecr.io/video-manager-signalrhub
    newTag: "1"
  - name: video-processor-application
    newName: vspsample.azurecr.io/video-processor-application
    newTag: "1"
  - name: video-store-api
    newName: vspsample.azurecr.io/video-store-api
    newTag: "1"
  - name: web-status
    newName: vspsample.azurecr.io/web-status
    newTag: "1"

generators:
  - "./generators/ingress-nginx.yml"

configMapGenerator:
  - name: common-config
    behavior: merge
    envs:
      - "./configs/common.env"
    
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: docker-config }]