apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  # - "./patches/video-processor-application/deployment.yml"
  - "./patches/persistence/storage-class.yml"
  - "./patches/storage-api/storage-class.yml"