apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"
  - "./resources/logstash/config-map.yml"
  - "./resources/jaeger/service.yml"
  - "./resources/jaeger/stateful-set.yml"

generators:
  - "./generators/rabbitmq.yml"
  - "./generators/mongodb.yml"
  - "./generators/postgres.yml"
  - "./generators/redis.yml"
  - "./generators/elasticsearch.yml"
  - "./generators/logstash.yml"

configMapGenerator:
  - name: common-config
    behavior: merge
    envs:
      - "./configs/common.env"
  - name: api-gateway-config
    behavior: merge
    envs:
      - "./configs/api-gateway.env"
  - name: identity-provider-config
    behavior: merge
    envs:
      - "./configs/identity-provider.env"
  - name: storage-api-config
    behavior: merge
    envs:
      - "./configs/storage-api.env"
  - name: video-processor-application-config
    behavior: merge
    envs:
      - "./configs/video-processor-application.env"

secretGenerator:
  - name: api-gateway-secret
    behavior: merge
    envs:
      - "./secrets/api-gateway.env"
  - name: community-api-secret
    behavior: merge
    envs:
      - "./secrets/community-api.env"
  - name: history-api-secret
    behavior: merge
    envs:
      - "./secrets/history-api.env"
  - name: identity-provider-secret
    behavior: merge
    envs:
      - "./secrets/identity-provider.env"
  - name: library-api-secret
    behavior: merge
    envs:
      - "./secrets/library-api.env"
  - name: search-api-secret
    behavior: merge
    envs:
      - "./secrets/search-api.env"
  - name: storage-api-secret
    behavior: merge
    envs:
      - "./secrets/storage-api.env"
  - name: subscriptions-api-secret
    behavior: merge
    envs:
      - "./secrets/subscriptions-api.env"
  - name: users-api-secret
    behavior: merge
    envs:
      - "./secrets/users-api.env"
  - name: video-manager-api-secret
    behavior: merge
    envs:
      - "./secrets/video-manager-api.env"
  - name: video-manager-signalrhub-secret
    behavior: merge
    envs:
      - "./secrets/video-manager-signalrhub.env"
  - name: video-processor-application-secret
    behavior: merge
    envs:
      - "./secrets/video-processor-application.env"
  - name: video-store-api-secret
    behavior: merge
    envs:
      - "./secrets/video-store-api.env"