apiVersion: apps/v1
kind: Deployment
metadata:
  name: vspclient
  labels:
    app: vspclient
spec:
  selector:
    matchLabels:
      app: vspclient
  template:
    metadata:
      labels:
        app: vspclient
    spec:
      containers:
      - name: vspclient
        image: vspclient
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1