apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"
  - "./resources/load-balancer.yml"

patchesStrategicMerge:
  - "./patches/deployment.yml"
  - "./patches/persistent-volume-claim.yml"
  - "./patches/storage-class.yml"

configMapGenerator:
  - name: storage-api-config
    behavior: merge
    envs:
      - "./patches/config-map.env"

secretGenerator:
  - name: storage-api-secret
    behavior: merge
    envs:
      - "./patches/secret.env"