apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-sc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true  