apiVersion: v1
kind: Service
metadata:
  name: video-manager-signalrhub
  labels:
    app: video-manager-signalrhub
spec:
  selector:
    app: video-manager-signalrhub
  ports:
  - protocol: TCP
    port: 80
    targetPort: http